name: Anchore Syft SBOM scan

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  actions: read

jobs:
  Anchore-Build-Scan:
    permissions:
      actions: read
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
      with:
        egress-policy: audit

    - name: Checkout the code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest
    - name: Scan the image and upload dependency results
      uses: anchore/sbom-action@9246b90769f852b3a8921f330c59e0b3f439d6e9 # v0.20.1
      with:
        image: "localbuild/testimage:latest"
        artifact-name: github.sbom.json
        dependency-snapshot: false
        format: cyclonedx
